version: '3.7'
services:
    postgres:
        image: postgres:13.1
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: apache/airflow:2.0.0-python3.8
        restart: always
        depends_on:
            - postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./mnt/airflow/dags:/usr/local/airflow/dags
            - ./mnt/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3