version: '3.7'
services:
    postgres:
        image: postgres:13.1
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        build: ./docker/airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/dags
            - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=https;AccountName=alphadatalake;AccountKey=T00js9CpaKfrSJVXmlBbYGufbuxOS6/U3M9OlBXSA6hkmfj/UEWLe3Ch/oP0fxA3yAyNegBuOioSgT4CWmuSRw==;EndpointSuffix=core.windows.net
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./mnt/airflow/dags:/usr/local/airflow/dags
        ports:
            - "8087:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3