apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: airflow
  template:
    metadata: 
      labels:
        component: airflow
    spec:
      containers:
        - name: airflow
          image: alphacontainerregistry.azurecr.io/alpha-airflow:latest
          ports:
            - containerPort: 8080
